name: Windows-CRD

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Test
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Authorise
      run: .\ngrok\ngrok.exe authtoken 1sZI6czJkSH6bZpavY37Sa4r14R_7R8n6DeGHory78QGyugK3
    - name: Property
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - name: Enable 
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Pro
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Set Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Kingxguru@00174" -Force)
    - name: Start Ngrok
      run: .\ngrok\ngrok.exe tcp 3389
