name: Windows-CRD

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Firewall
      run: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
    - name: Chrome Remote Desktop Download
      run: & {$P = $env:TEMP + '\chromeremotedesktophost.msi'; Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P; Start-Process $P -Wait; Remove-Item $P}
    - name: Chrome Download
      run: & {$P = $env:TEMP + '\chrome_installer.exe'; Invoke-WebRequest 'https://dl.google.com/chrome/install/latest/chrome_installer.exe' -OutFile $P; Start-Process -FilePath $P -Args '/install' -Verb RunAs -Wait; Remove-Item $P}
    - name: Start
      run: & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0AY0e-g65aeZOsN7xvFhn3uvD5suN0fInhUgNP8OlPjBI1RSaXNfoI5swJeX7pr0cucv4pA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME -pin=131213
    - name: TimeOut
      run: $i = 360
do {
    Write-Host $i
    Sleep 60
    $i--
} while ($i -gt 0)
